#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse

import commata

def main():
    parser = argparse.ArgumentParser(
        description = 'An interpreter for the ,,, language.')
    parser.add_argument('file', help = 'program read from script file',
                        type = open)
    parser.add_argument('args', help = 'arguments for the script',
                        nargs = argparse.REMAINDER)

    arguments = parser.parse_args()
    with arguments.file as f:
        commata.run(f.read(), arguments.args)


if __name__ == '__main__':
    main()
